"""add reminder tracking fields and shortage status table

Revision ID: 1997d5549d18
Revises: 94a28bdab909
Create Date: 2026-07-25 18:15:25.580111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1997d5549d18'
down_revision: Union[str, Sequence[str], None] = '94a28bdab909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shortage_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medication_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shortage_status_id'), 'shortage_status', ['id'], unique=False)
    op.create_index(op.f('ix_shortage_status_medication_name'), 'shortage_status', ['medication_name'], unique=True)
    op.add_column('call_logs', sa.Column('checkback_reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('refill_countdowns', sa.Column('last_reminder_sent_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refill_countdowns', 'last_reminder_sent_at')
    op.drop_column('call_logs', 'checkback_reminder_sent_at')
    op.drop_index(op.f('ix_shortage_status_medication_name'), table_name='shortage_status')
    op.drop_index(op.f('ix_shortage_status_id'), table_name='shortage_status')
    op.drop_table('shortage_status')
    # ### end Alembic commands ###
