"""add expected restock date and private call notes

Revision ID: 3b6621c306ac
Revises: 3552729b95ec
Create Date: 2026-07-24 23:01:52.975920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b6621c306ac'
down_revision: Union[str, Sequence[str], None] = '3552729b95ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('availability_reports', sa.Column('expected_restock_date', sa.Date(), nullable=True))
    op.add_column('call_logs', sa.Column('expected_restock_date', sa.Date(), nullable=True))
    op.add_column('call_logs', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('call_logs', sa.Column('manufacturer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_logs', 'manufacturer')
    op.drop_column('call_logs', 'notes')
    op.drop_column('call_logs', 'expected_restock_date')
    op.drop_column('availability_reports', 'expected_restock_date')
    # ### end Alembic commands ###
