"""initial schema

Revision ID: 5fb582ffff19
Revises: 
Create Date: 2026-06-08 17:28:34.139982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fb582ffff19'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('apple_sub', sa.String(), nullable=True),
    sa.Column('google_sub', sa.String(), nullable=True),
    sa.Column('caregiver_mode', sa.Boolean(), nullable=True),
    sa.Column('subscription_tier', sa.Enum('free', 'contributor', 'premium', name='subscriptiontier'), nullable=True),
    sa.Column('last_contribution_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('push_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_apple_sub'), 'users', ['apple_sub'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('alert_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('radius_miles', sa.Integer(), nullable=True),
    sa.Column('quiet_hours_start', sa.Integer(), nullable=True),
    sa.Column('quiet_hours_end', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_alert_settings_id'), 'alert_settings', ['id'], unique=False)
    op.create_table('availability_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pharmacy_name', sa.String(), nullable=False),
    sa.Column('pharmacy_address', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('medication_name', sa.String(), nullable=False),
    sa.Column('strength', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('in_stock', 'out_of_stock', 'check_back', 'unknown', name='callstatus'), nullable=False),
    sa.Column('source', sa.Enum('community', 'fda', 'ashp', name='reportsource'), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_reports_id'), 'availability_reports', ['id'], unique=False)
    op.create_index(op.f('ix_availability_reports_reported_at'), 'availability_reports', ['reported_at'], unique=False)
    op.create_index(op.f('ix_availability_reports_zip_code'), 'availability_reports', ['zip_code'], unique=False)
    op.create_table('medication_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('medication_name', sa.String(), nullable=False),
    sa.Column('strength', sa.String(), nullable=False),
    sa.Column('formulation', sa.String(), nullable=True),
    sa.Column('is_child_profile', sa.Boolean(), nullable=True),
    sa.Column('child_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_profiles_id'), 'medication_profiles', ['id'], unique=False)
    op.create_table('pharmacies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('is_vaulted', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacies_id'), 'pharmacies', ['id'], unique=False)
    op.create_table('call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_id', sa.Integer(), nullable=False),
    sa.Column('called_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('status', sa.Enum('in_stock', 'out_of_stock', 'check_back', 'unknown', name='callstatus'), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.String(), nullable=True),
    sa.Column('extracted_restock_date', sa.Date(), nullable=True),
    sa.Column('extracted_strength', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('contributed_to_community', sa.Boolean(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_logs_id'), 'call_logs', ['id'], unique=False)
    op.create_table('refill_countdowns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('medication_profile_id', sa.Integer(), nullable=True),
    sa.Column('last_fill_date', sa.Date(), nullable=True),
    sa.Column('days_supply', sa.Integer(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('push_notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['medication_profile_id'], ['medication_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_refill_countdowns_id'), 'refill_countdowns', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refill_countdowns_id'), table_name='refill_countdowns')
    op.drop_table('refill_countdowns')
    op.drop_index(op.f('ix_call_logs_id'), table_name='call_logs')
    op.drop_table('call_logs')
    op.drop_index(op.f('ix_pharmacies_id'), table_name='pharmacies')
    op.drop_table('pharmacies')
    op.drop_index(op.f('ix_medication_profiles_id'), table_name='medication_profiles')
    op.drop_table('medication_profiles')
    op.drop_index(op.f('ix_availability_reports_zip_code'), table_name='availability_reports')
    op.drop_index(op.f('ix_availability_reports_reported_at'), table_name='availability_reports')
    op.drop_index(op.f('ix_availability_reports_id'), table_name='availability_reports')
    op.drop_table('availability_reports')
    op.drop_index(op.f('ix_alert_settings_id'), table_name='alert_settings')
    op.drop_table('alert_settings')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_apple_sub'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
